### ISSUE TITLE
Scraping and tidying of data should be scripted

### ISSUE THREAD

**Issue by rufuspollock** [subhankarb/pharmaceutical-spending#5]
Should be in `/scripts/process.py` by convention.

**Comment by subhankarb** [comment]
FIXED.

**Comment by rufuspollock** [comment]
@subhankarb the reference commit does not fix this issue at all. The issue is the lack of scripting of the data download and retrieval. Where does this data get downloaded from? Does it need to be cleaned up prior to the processing you currently do?

This should all be scripted.

Please REOPEN.
